/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    Api: {
      type: "sst.cloudflare.Worker"
      url: string
    }
    Bucket: {
      type: "sst.cloudflare.Bucket"
    }
    Web: {
      type: "sst.cloudflare.StaticSite"
      url: string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}
